### ISSUE TITLE
Entwicklungssprint

### ISSUE THREAD

**Issue by therter** [cismet/belis-online#14]
- [x] add infoBox (#2 )
- [x] Create a factoy method to resolve foreign key dependencies (#13)
- [x] add secondary InfoBox (#3 )
- [ ] Report malfunction dialogue (#4)
- [ ] Task Protocol Status Dialogue (#5)
- [ ] Task Protocol Actions Dialogues (#6)
- [x] Switch to JWT Auth (#7)
- [x] Switch to Graphql Action (#8)
- [x] Syncing UI (#10)
