### ISSUE TITLE
Bugfixes during test phase

### ISSUE THREAD

**Issue by therter** [cismet/belis-online#21]
- [x] Cannot read property of undefined (see https://github.com/cismet/wupp/issues/2523 and https://github.com/cismet/wupp/issues/2513)
- [x] misspelling (see https://github.com/cismet/wupp/issues/2516)
- [x] typo in property (see https://github.com/cismet/wupp/issues/2521)
- [x] no dk pk's in leuchte Info Sheet (see https://github.com/cismet/wupp/issues/2517)
- [x] don't show the lightbox in Arbeitsauftrag Infosheet (see https://github.com/cismet/wupp/issues/2515)
- [x] z-index jam on certain conditions
- [x] showing tasklists of team that is not selected
